filter:
    excluded_paths:
        - Tests/*
        - vendor/*
tools:
    # external_code_coverage:
    #     timeout: 1800
    #     runs: 5
    php_changetracking: true
    php_mess_detector: true
    php_code_sniffer:
        config:
            standard: PSR1
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend: true
    php_loc: true
    php_cpd: true
    php_sim: true
    php_cs_fixer: true
    php_analyzer: true
